spring:
  datasource:
    url: jdbc:h2:~/mydb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    #url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true
    username: sa
    password: password
    driverClassName: org.h2.Driver
    #driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher